#
# ATENÇÃO: Não apague esse arquivo
# Ele é usado pelo time do gb.tech para termos o catalogo dinâmico de aplicações
#

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "terraform-aws-elasticsearch"
  description: >
    AWS Terraform Elasticsearch
  tags:
    - "infra"
    - "aws"
  annotations:
    github.com/project-slug: "grupoboticario/terraform-aws-elasticsearch"
    github.com/team-slug: "grupoboticario/sre"
spec:
  type: non-standard
  lifecycle: "production"
  owner: "sre"
  system: "infra-core"
  domain: "infraestrutura"
